package com.JJ.model;

import java.io.Serializable;

public class AppUser implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.email
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.enabled
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.firstName
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.lastName
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.name
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.password
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.profileImage
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    private String profileimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.email
     *
     * @return the value of app_user.email
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.email
     *
     * @param email the value for app_user.email
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.enabled
     *
     * @return the value of app_user.enabled
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.enabled
     *
     * @param enabled the value for app_user.enabled
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.firstName
     *
     * @return the value of app_user.firstName
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.firstName
     *
     * @param firstname the value for app_user.firstName
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.lastName
     *
     * @return the value of app_user.lastName
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.lastName
     *
     * @param lastname the value for app_user.lastName
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.name
     *
     * @return the value of app_user.name
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.name
     *
     * @param name the value for app_user.name
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password
     *
     * @return the value of app_user.password
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password
     *
     * @param password the value for app_user.password
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.profileImage
     *
     * @return the value of app_user.profileImage
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public String getProfileimage() {
        return profileimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.profileImage
     *
     * @param profileimage the value for app_user.profileImage
     *
     * @mbggenerated Sat Oct 08 13:35:38 SGT 2016
     */
    public void setProfileimage(String profileimage) {
        this.profileimage = profileimage;
    }
    
    @Override
    public String toString(){
		return "AppUser [ firstname = " + firstname + ", lastname = " + lastname + ", email = " + email
				+ ", name = " + name + ", password = " + password + ", enabled = " + enabled + " ]";
    	
    }
}