package com.JJ.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BatchstockintakeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public BatchstockintakeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBatchidIsNull() {
			addCriterion("batchid is null");
			return (Criteria) this;
		}

		public Criteria andBatchidIsNotNull() {
			addCriterion("batchid is not null");
			return (Criteria) this;
		}

		public Criteria andBatchidEqualTo(Integer value) {
			addCriterion("batchid =", value, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidNotEqualTo(Integer value) {
			addCriterion("batchid <>", value, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidGreaterThan(Integer value) {
			addCriterion("batchid >", value, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidGreaterThanOrEqualTo(Integer value) {
			addCriterion("batchid >=", value, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidLessThan(Integer value) {
			addCriterion("batchid <", value, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidLessThanOrEqualTo(Integer value) {
			addCriterion("batchid <=", value, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidIn(List<Integer> values) {
			addCriterion("batchid in", values, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidNotIn(List<Integer> values) {
			addCriterion("batchid not in", values, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidBetween(Integer value1, Integer value2) {
			addCriterion("batchid between", value1, value2, "batchid");
			return (Criteria) this;
		}

		public Criteria andBatchidNotBetween(Integer value1, Integer value2) {
			addCriterion("batchid not between", value1, value2, "batchid");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("remarks like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("remarks not like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<String> values) {
			addCriterion("remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<String> values) {
			addCriterion("remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andDateIsNull() {
			addCriterion("date is null");
			return (Criteria) this;
		}

		public Criteria andDateIsNotNull() {
			addCriterion("date is not null");
			return (Criteria) this;
		}

		public Criteria andDateEqualTo(Date value) {
			addCriterion("date =", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotEqualTo(Date value) {
			addCriterion("date <>", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThan(Date value) {
			addCriterion("date >", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThanOrEqualTo(Date value) {
			addCriterion("date >=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThan(Date value) {
			addCriterion("date <", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThanOrEqualTo(Date value) {
			addCriterion("date <=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateIn(List<Date> values) {
			addCriterion("date in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotIn(List<Date> values) {
			addCriterion("date not in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateBetween(Date value1, Date value2) {
			addCriterion("date between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotBetween(Date value1, Date value2) {
			addCriterion("date not between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andStoragelocationIsNull() {
			addCriterion("storagelocation is null");
			return (Criteria) this;
		}

		public Criteria andStoragelocationIsNotNull() {
			addCriterion("storagelocation is not null");
			return (Criteria) this;
		}

		public Criteria andStoragelocationEqualTo(Integer value) {
			addCriterion("storagelocation =", value, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationNotEqualTo(Integer value) {
			addCriterion("storagelocation <>", value, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationGreaterThan(Integer value) {
			addCriterion("storagelocation >", value, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationGreaterThanOrEqualTo(Integer value) {
			addCriterion("storagelocation >=", value, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationLessThan(Integer value) {
			addCriterion("storagelocation <", value, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationLessThanOrEqualTo(Integer value) {
			addCriterion("storagelocation <=", value, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationIn(List<Integer> values) {
			addCriterion("storagelocation in", values, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationNotIn(List<Integer> values) {
			addCriterion("storagelocation not in", values, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationBetween(Integer value1, Integer value2) {
			addCriterion("storagelocation between", value1, value2, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andStoragelocationNotBetween(Integer value1, Integer value2) {
			addCriterion("storagelocation not between", value1, value2, "storagelocation");
			return (Criteria) this;
		}

		public Criteria andTotalcostIsNull() {
			addCriterion("totalcost is null");
			return (Criteria) this;
		}

		public Criteria andTotalcostIsNotNull() {
			addCriterion("totalcost is not null");
			return (Criteria) this;
		}

		public Criteria andTotalcostEqualTo(BigDecimal value) {
			addCriterion("totalcost =", value, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostNotEqualTo(BigDecimal value) {
			addCriterion("totalcost <>", value, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostGreaterThan(BigDecimal value) {
			addCriterion("totalcost >", value, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("totalcost >=", value, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostLessThan(BigDecimal value) {
			addCriterion("totalcost <", value, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostLessThanOrEqualTo(BigDecimal value) {
			addCriterion("totalcost <=", value, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostIn(List<BigDecimal> values) {
			addCriterion("totalcost in", values, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostNotIn(List<BigDecimal> values) {
			addCriterion("totalcost not in", values, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalcost between", value1, value2, "totalcost");
			return (Criteria) this;
		}

		public Criteria andTotalcostNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalcost not between", value1, value2, "totalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostIsNull() {
			addCriterion("additionalcost is null");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostIsNotNull() {
			addCriterion("additionalcost is not null");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostEqualTo(BigDecimal value) {
			addCriterion("additionalcost =", value, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostNotEqualTo(BigDecimal value) {
			addCriterion("additionalcost <>", value, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostGreaterThan(BigDecimal value) {
			addCriterion("additionalcost >", value, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("additionalcost >=", value, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostLessThan(BigDecimal value) {
			addCriterion("additionalcost <", value, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostLessThanOrEqualTo(BigDecimal value) {
			addCriterion("additionalcost <=", value, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostIn(List<BigDecimal> values) {
			addCriterion("additionalcost in", values, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostNotIn(List<BigDecimal> values) {
			addCriterion("additionalcost not in", values, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("additionalcost between", value1, value2, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andAdditionalcostNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("additionalcost not between", value1, value2, "additionalcost");
			return (Criteria) this;
		}

		public Criteria andDeleteindIsNull() {
			addCriterion("deleteind is null");
			return (Criteria) this;
		}

		public Criteria andDeleteindIsNotNull() {
			addCriterion("deleteind is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteindEqualTo(String value) {
			addCriterion("deleteind =", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotEqualTo(String value) {
			addCriterion("deleteind <>", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindGreaterThan(String value) {
			addCriterion("deleteind >", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindGreaterThanOrEqualTo(String value) {
			addCriterion("deleteind >=", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindLessThan(String value) {
			addCriterion("deleteind <", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindLessThanOrEqualTo(String value) {
			addCriterion("deleteind <=", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindLike(String value) {
			addCriterion("deleteind like", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotLike(String value) {
			addCriterion("deleteind not like", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindIn(List<String> values) {
			addCriterion("deleteind in", values, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotIn(List<String> values) {
			addCriterion("deleteind not in", values, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindBetween(String value1, String value2) {
			addCriterion("deleteind between", value1, value2, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotBetween(String value1, String value2) {
			addCriterion("deleteind not between", value1, value2, "deleteind");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyIsNull() {
			addCriterion("updatedby is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyIsNotNull() {
			addCriterion("updatedby is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyEqualTo(String value) {
			addCriterion("updatedby =", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotEqualTo(String value) {
			addCriterion("updatedby <>", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyGreaterThan(String value) {
			addCriterion("updatedby >", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("updatedby >=", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyLessThan(String value) {
			addCriterion("updatedby <", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyLessThanOrEqualTo(String value) {
			addCriterion("updatedby <=", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyLike(String value) {
			addCriterion("updatedby like", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotLike(String value) {
			addCriterion("updatedby not like", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyIn(List<String> values) {
			addCriterion("updatedby in", values, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotIn(List<String> values) {
			addCriterion("updatedby not in", values, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyBetween(String value1, String value2) {
			addCriterion("updatedby between", value1, value2, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotBetween(String value1, String value2) {
			addCriterion("updatedby not between", value1, value2, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedonIsNull() {
			addCriterion("updatedon is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedonIsNotNull() {
			addCriterion("updatedon is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedonEqualTo(Date value) {
			addCriterion("updatedon =", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonNotEqualTo(Date value) {
			addCriterion("updatedon <>", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonGreaterThan(Date value) {
			addCriterion("updatedon >", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonGreaterThanOrEqualTo(Date value) {
			addCriterion("updatedon >=", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonLessThan(Date value) {
			addCriterion("updatedon <", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonLessThanOrEqualTo(Date value) {
			addCriterion("updatedon <=", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonIn(List<Date> values) {
			addCriterion("updatedon in", values, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonNotIn(List<Date> values) {
			addCriterion("updatedon not in", values, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonBetween(Date value1, Date value2) {
			addCriterion("updatedon between", value1, value2, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonNotBetween(Date value1, Date value2) {
			addCriterion("updatedon not between", value1, value2, "updatedon");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNull() {
			addCriterion("createdby is null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNotNull() {
			addCriterion("createdby is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyEqualTo(String value) {
			addCriterion("createdby =", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotEqualTo(String value) {
			addCriterion("createdby <>", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThan(String value) {
			addCriterion("createdby >", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("createdby >=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThan(String value) {
			addCriterion("createdby <", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThanOrEqualTo(String value) {
			addCriterion("createdby <=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLike(String value) {
			addCriterion("createdby like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotLike(String value) {
			addCriterion("createdby not like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIn(List<String> values) {
			addCriterion("createdby in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotIn(List<String> values) {
			addCriterion("createdby not in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyBetween(String value1, String value2) {
			addCriterion("createdby between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotBetween(String value1, String value2) {
			addCriterion("createdby not between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedonIsNull() {
			addCriterion("createdon is null");
			return (Criteria) this;
		}

		public Criteria andCreatedonIsNotNull() {
			addCriterion("createdon is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedonEqualTo(Date value) {
			addCriterion("createdon =", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonNotEqualTo(Date value) {
			addCriterion("createdon <>", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonGreaterThan(Date value) {
			addCriterion("createdon >", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonGreaterThanOrEqualTo(Date value) {
			addCriterion("createdon >=", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonLessThan(Date value) {
			addCriterion("createdon <", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonLessThanOrEqualTo(Date value) {
			addCriterion("createdon <=", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonIn(List<Date> values) {
			addCriterion("createdon in", values, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonNotIn(List<Date> values) {
			addCriterion("createdon not in", values, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonBetween(Date value1, Date value2) {
			addCriterion("createdon between", value1, value2, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonNotBetween(Date value1, Date value2) {
			addCriterion("createdon not between", value1, value2, "createdon");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table batchstockintake
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 20 16:58:03 SGT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}