package com.JJ.model;

import java.math.BigDecimal;

public class BatchproductRs extends Base{
    @Override
	public String toString() {
		return "BatchproductRs [batchproductid=" + batchproductid + ", batchid=" + batchid + ", productid=" + productid
				+ ", productsuboption1id=" + productsuboption1id + ", productsuboption2id=" + productsuboption2id
				+ ", productsuboption3id=" + productsuboption3id + ", unitcost=" + unitcost + ", qty=" + qty + "]";
	}

	public BatchproductRs() {
		super();
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.batchproductid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer batchproductid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.batchid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer batchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.productid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.productsuboption1id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer productsuboption1id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.productsuboption2id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer productsuboption2id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.productsuboption3id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer productsuboption3id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.unitcost
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private BigDecimal unitcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batchproduct_rs.qty
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.batchproductid
     *
     * @return the value of batchproduct_rs.batchproductid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getBatchproductid() {
        return batchproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.batchproductid
     *
     * @param batchproductid the value for batchproduct_rs.batchproductid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setBatchproductid(Integer batchproductid) {
        this.batchproductid = batchproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.batchid
     *
     * @return the value of batchproduct_rs.batchid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.batchid
     *
     * @param batchid the value for batchproduct_rs.batchid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setBatchid(Integer batchid) {
        this.batchid = batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.productid
     *
     * @return the value of batchproduct_rs.productid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.productid
     *
     * @param productid the value for batchproduct_rs.productid
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.productsuboption1id
     *
     * @return the value of batchproduct_rs.productsuboption1id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getProductsuboption1id() {
        return productsuboption1id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.productsuboption1id
     *
     * @param productsuboption1id the value for batchproduct_rs.productsuboption1id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setProductsuboption1id(Integer productsuboption1id) {
        this.productsuboption1id = productsuboption1id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.productsuboption2id
     *
     * @return the value of batchproduct_rs.productsuboption2id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getProductsuboption2id() {
        return productsuboption2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.productsuboption2id
     *
     * @param productsuboption2id the value for batchproduct_rs.productsuboption2id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setProductsuboption2id(Integer productsuboption2id) {
        this.productsuboption2id = productsuboption2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.productsuboption3id
     *
     * @return the value of batchproduct_rs.productsuboption3id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getProductsuboption3id() {
        return productsuboption3id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.productsuboption3id
     *
     * @param productsuboption3id the value for batchproduct_rs.productsuboption3id
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setProductsuboption3id(Integer productsuboption3id) {
        this.productsuboption3id = productsuboption3id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.unitcost
     *
     * @return the value of batchproduct_rs.unitcost
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public BigDecimal getUnitcost() {
        return unitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.unitcost
     *
     * @param unitcost the value for batchproduct_rs.unitcost
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setUnitcost(BigDecimal unitcost) {
        this.unitcost = unitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batchproduct_rs.qty
     *
     * @return the value of batchproduct_rs.qty
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batchproduct_rs.qty
     *
     * @param qty the value for batchproduct_rs.qty
     *
     * @mbggenerated Sun Nov 20 16:58:23 SGT 2016
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}