package com.JJ.model;

import java.math.BigDecimal;
import java.util.Date;

public class Batchstockintake extends Base{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public Batchstockintake() {
		super();
	}

	@Override
	public String toString() {
		return "Batchstockintake [batchid=" + batchid + ", remarks=" + remarks + ", date=" + date + ", storagelocation="
				+ storagelocation + ", totalcost=" + totalcost + ", additionalcost=" + additionalcost + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column batchstockintake.batchid
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	private Integer batchid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column batchstockintake.remarks
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column batchstockintake.date
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column batchstockintake.storagelocation
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	private Integer storagelocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column batchstockintake.totalcost
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	private BigDecimal totalcost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column batchstockintake.additionalcost
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	private BigDecimal additionalcost;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column batchstockintake.batchid
	 * @return  the value of batchstockintake.batchid
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public Integer getBatchid() {
		return batchid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column batchstockintake.batchid
	 * @param batchid  the value for batchstockintake.batchid
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setBatchid(Integer batchid) {
		this.batchid = batchid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column batchstockintake.remarks
	 * @return  the value of batchstockintake.remarks
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column batchstockintake.remarks
	 * @param remarks  the value for batchstockintake.remarks
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column batchstockintake.date
	 * @return  the value of batchstockintake.date
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column batchstockintake.date
	 * @param date  the value for batchstockintake.date
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column batchstockintake.storagelocation
	 * @return  the value of batchstockintake.storagelocation
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public Integer getStoragelocation() {
		return storagelocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column batchstockintake.storagelocation
	 * @param storagelocation  the value for batchstockintake.storagelocation
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setStoragelocation(Integer storagelocation) {
		this.storagelocation = storagelocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column batchstockintake.totalcost
	 * @return  the value of batchstockintake.totalcost
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public BigDecimal getTotalcost() {
		return totalcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column batchstockintake.totalcost
	 * @param totalcost  the value for batchstockintake.totalcost
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setTotalcost(BigDecimal totalcost) {
		this.totalcost = totalcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column batchstockintake.additionalcost
	 * @return  the value of batchstockintake.additionalcost
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public BigDecimal getAdditionalcost() {
		return additionalcost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column batchstockintake.additionalcost
	 * @param additionalcost  the value for batchstockintake.additionalcost
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	public void setAdditionalcost(BigDecimal additionalcost) {
		this.additionalcost = additionalcost;
	}
	
	//non db fields
	private String storagelocationname;
	
	public String getStoragelocationname() {
		return storagelocationname;
	}

	public void setStoragelocationname(String storagelocationname) {
		this.storagelocationname = storagelocationname;
	}
	
}