package com.JJ.model;

public class Customeraddress extends Base{

	public Customeraddress(){
		super();
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.addressId
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private Integer addressid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.customerId
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private Integer customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.recipientName
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private String recipientname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.address
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.contactNumber
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private Long contactnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.postalCode
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private Integer postalcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.country
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customeraddress.defaultInd
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	private String defaultind;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.addressId
	 * @return  the value of customeraddress.addressId
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public Integer getAddressid() {
		return addressid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.addressId
	 * @param addressid  the value for customeraddress.addressId
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setAddressid(Integer addressid) {
		this.addressid = addressid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.customerId
	 * @return  the value of customeraddress.customerId
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public Integer getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.customerId
	 * @param customerid  the value for customeraddress.customerId
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.recipientName
	 * @return  the value of customeraddress.recipientName
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public String getRecipientname() {
		return recipientname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.recipientName
	 * @param recipientname  the value for customeraddress.recipientName
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setRecipientname(String recipientname) {
		this.recipientname = recipientname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.address
	 * @return  the value of customeraddress.address
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.address
	 * @param address  the value for customeraddress.address
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.contactNumber
	 * @return  the value of customeraddress.contactNumber
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public Long getContactnumber() {
		return contactnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.contactNumber
	 * @param contactnumber  the value for customeraddress.contactNumber
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setContactnumber(Long contactnumber) {
		this.contactnumber = contactnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.postalCode
	 * @return  the value of customeraddress.postalCode
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public Integer getPostalcode() {
		return postalcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.postalCode
	 * @param postalcode  the value for customeraddress.postalCode
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setPostalcode(Integer postalcode) {
		this.postalcode = postalcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.country
	 * @return  the value of customeraddress.country
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.country
	 * @param country  the value for customeraddress.country
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customeraddress.defaultInd
	 * @return  the value of customeraddress.defaultInd
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public String getDefaultind() {
		return defaultind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customeraddress.defaultInd
	 * @param defaultind  the value for customeraddress.defaultInd
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setDefaultind(String defaultind) {
		this.defaultind = defaultind;
	}
}