package com.JJ.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomeraddressExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public CustomeraddressExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAddressidIsNull() {
			addCriterion("addressId is null");
			return (Criteria) this;
		}

		public Criteria andAddressidIsNotNull() {
			addCriterion("addressId is not null");
			return (Criteria) this;
		}

		public Criteria andAddressidEqualTo(Integer value) {
			addCriterion("addressId =", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidNotEqualTo(Integer value) {
			addCriterion("addressId <>", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidGreaterThan(Integer value) {
			addCriterion("addressId >", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidGreaterThanOrEqualTo(Integer value) {
			addCriterion("addressId >=", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidLessThan(Integer value) {
			addCriterion("addressId <", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidLessThanOrEqualTo(Integer value) {
			addCriterion("addressId <=", value, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidIn(List<Integer> values) {
			addCriterion("addressId in", values, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidNotIn(List<Integer> values) {
			addCriterion("addressId not in", values, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidBetween(Integer value1, Integer value2) {
			addCriterion("addressId between", value1, value2, "addressid");
			return (Criteria) this;
		}

		public Criteria andAddressidNotBetween(Integer value1, Integer value2) {
			addCriterion("addressId not between", value1, value2, "addressid");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNull() {
			addCriterion("customerId is null");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNotNull() {
			addCriterion("customerId is not null");
			return (Criteria) this;
		}

		public Criteria andCustomeridEqualTo(Integer value) {
			addCriterion("customerId =", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotEqualTo(Integer value) {
			addCriterion("customerId <>", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThan(Integer value) {
			addCriterion("customerId >", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThanOrEqualTo(Integer value) {
			addCriterion("customerId >=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThan(Integer value) {
			addCriterion("customerId <", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThanOrEqualTo(Integer value) {
			addCriterion("customerId <=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridIn(List<Integer> values) {
			addCriterion("customerId in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotIn(List<Integer> values) {
			addCriterion("customerId not in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridBetween(Integer value1, Integer value2) {
			addCriterion("customerId between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotBetween(Integer value1, Integer value2) {
			addCriterion("customerId not between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andRecipientnameIsNull() {
			addCriterion("recipientName is null");
			return (Criteria) this;
		}

		public Criteria andRecipientnameIsNotNull() {
			addCriterion("recipientName is not null");
			return (Criteria) this;
		}

		public Criteria andRecipientnameEqualTo(String value) {
			addCriterion("recipientName =", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameNotEqualTo(String value) {
			addCriterion("recipientName <>", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameGreaterThan(String value) {
			addCriterion("recipientName >", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameGreaterThanOrEqualTo(String value) {
			addCriterion("recipientName >=", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameLessThan(String value) {
			addCriterion("recipientName <", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameLessThanOrEqualTo(String value) {
			addCriterion("recipientName <=", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameLike(String value) {
			addCriterion("recipientName like", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameNotLike(String value) {
			addCriterion("recipientName not like", value, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameIn(List<String> values) {
			addCriterion("recipientName in", values, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameNotIn(List<String> values) {
			addCriterion("recipientName not in", values, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameBetween(String value1, String value2) {
			addCriterion("recipientName between", value1, value2, "recipientname");
			return (Criteria) this;
		}

		public Criteria andRecipientnameNotBetween(String value1, String value2) {
			addCriterion("recipientName not between", value1, value2, "recipientname");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andContactnumberIsNull() {
			addCriterion("contactNumber is null");
			return (Criteria) this;
		}

		public Criteria andContactnumberIsNotNull() {
			addCriterion("contactNumber is not null");
			return (Criteria) this;
		}

		public Criteria andContactnumberEqualTo(Long value) {
			addCriterion("contactNumber =", value, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberNotEqualTo(Long value) {
			addCriterion("contactNumber <>", value, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberGreaterThan(Long value) {
			addCriterion("contactNumber >", value, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberGreaterThanOrEqualTo(Long value) {
			addCriterion("contactNumber >=", value, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberLessThan(Long value) {
			addCriterion("contactNumber <", value, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberLessThanOrEqualTo(Long value) {
			addCriterion("contactNumber <=", value, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberIn(List<Long> values) {
			addCriterion("contactNumber in", values, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberNotIn(List<Long> values) {
			addCriterion("contactNumber not in", values, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberBetween(Long value1, Long value2) {
			addCriterion("contactNumber between", value1, value2, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andContactnumberNotBetween(Long value1, Long value2) {
			addCriterion("contactNumber not between", value1, value2, "contactnumber");
			return (Criteria) this;
		}

		public Criteria andPostalcodeIsNull() {
			addCriterion("postalCode is null");
			return (Criteria) this;
		}

		public Criteria andPostalcodeIsNotNull() {
			addCriterion("postalCode is not null");
			return (Criteria) this;
		}

		public Criteria andPostalcodeEqualTo(Integer value) {
			addCriterion("postalCode =", value, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeNotEqualTo(Integer value) {
			addCriterion("postalCode <>", value, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeGreaterThan(Integer value) {
			addCriterion("postalCode >", value, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("postalCode >=", value, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeLessThan(Integer value) {
			addCriterion("postalCode <", value, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeLessThanOrEqualTo(Integer value) {
			addCriterion("postalCode <=", value, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeIn(List<Integer> values) {
			addCriterion("postalCode in", values, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeNotIn(List<Integer> values) {
			addCriterion("postalCode not in", values, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeBetween(Integer value1, Integer value2) {
			addCriterion("postalCode between", value1, value2, "postalcode");
			return (Criteria) this;
		}

		public Criteria andPostalcodeNotBetween(Integer value1, Integer value2) {
			addCriterion("postalCode not between", value1, value2, "postalcode");
			return (Criteria) this;
		}

		public Criteria andCountryIsNull() {
			addCriterion("country is null");
			return (Criteria) this;
		}

		public Criteria andCountryIsNotNull() {
			addCriterion("country is not null");
			return (Criteria) this;
		}

		public Criteria andCountryEqualTo(String value) {
			addCriterion("country =", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotEqualTo(String value) {
			addCriterion("country <>", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThan(String value) {
			addCriterion("country >", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThanOrEqualTo(String value) {
			addCriterion("country >=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThan(String value) {
			addCriterion("country <", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThanOrEqualTo(String value) {
			addCriterion("country <=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLike(String value) {
			addCriterion("country like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotLike(String value) {
			addCriterion("country not like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryIn(List<String> values) {
			addCriterion("country in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotIn(List<String> values) {
			addCriterion("country not in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryBetween(String value1, String value2) {
			addCriterion("country between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotBetween(String value1, String value2) {
			addCriterion("country not between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andDefaultindIsNull() {
			addCriterion("defaultInd is null");
			return (Criteria) this;
		}

		public Criteria andDefaultindIsNotNull() {
			addCriterion("defaultInd is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultindEqualTo(String value) {
			addCriterion("defaultInd =", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindNotEqualTo(String value) {
			addCriterion("defaultInd <>", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindGreaterThan(String value) {
			addCriterion("defaultInd >", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindGreaterThanOrEqualTo(String value) {
			addCriterion("defaultInd >=", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindLessThan(String value) {
			addCriterion("defaultInd <", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindLessThanOrEqualTo(String value) {
			addCriterion("defaultInd <=", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindLike(String value) {
			addCriterion("defaultInd like", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindNotLike(String value) {
			addCriterion("defaultInd not like", value, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindIn(List<String> values) {
			addCriterion("defaultInd in", values, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindNotIn(List<String> values) {
			addCriterion("defaultInd not in", values, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindBetween(String value1, String value2) {
			addCriterion("defaultInd between", value1, value2, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDefaultindNotBetween(String value1, String value2) {
			addCriterion("defaultInd not between", value1, value2, "defaultind");
			return (Criteria) this;
		}

		public Criteria andDeleteindIsNull() {
			addCriterion("deleteInd is null");
			return (Criteria) this;
		}

		public Criteria andDeleteindIsNotNull() {
			addCriterion("deleteInd is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteindEqualTo(String value) {
			addCriterion("deleteInd =", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotEqualTo(String value) {
			addCriterion("deleteInd <>", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindGreaterThan(String value) {
			addCriterion("deleteInd >", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindGreaterThanOrEqualTo(String value) {
			addCriterion("deleteInd >=", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindLessThan(String value) {
			addCriterion("deleteInd <", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindLessThanOrEqualTo(String value) {
			addCriterion("deleteInd <=", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindLike(String value) {
			addCriterion("deleteInd like", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotLike(String value) {
			addCriterion("deleteInd not like", value, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindIn(List<String> values) {
			addCriterion("deleteInd in", values, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotIn(List<String> values) {
			addCriterion("deleteInd not in", values, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindBetween(String value1, String value2) {
			addCriterion("deleteInd between", value1, value2, "deleteind");
			return (Criteria) this;
		}

		public Criteria andDeleteindNotBetween(String value1, String value2) {
			addCriterion("deleteInd not between", value1, value2, "deleteind");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNull() {
			addCriterion("createdby is null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNotNull() {
			addCriterion("createdby is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyEqualTo(String value) {
			addCriterion("createdby =", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotEqualTo(String value) {
			addCriterion("createdby <>", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThan(String value) {
			addCriterion("createdby >", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("createdby >=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThan(String value) {
			addCriterion("createdby <", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThanOrEqualTo(String value) {
			addCriterion("createdby <=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLike(String value) {
			addCriterion("createdby like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotLike(String value) {
			addCriterion("createdby not like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIn(List<String> values) {
			addCriterion("createdby in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotIn(List<String> values) {
			addCriterion("createdby not in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyBetween(String value1, String value2) {
			addCriterion("createdby between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotBetween(String value1, String value2) {
			addCriterion("createdby not between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedonIsNull() {
			addCriterion("createdon is null");
			return (Criteria) this;
		}

		public Criteria andCreatedonIsNotNull() {
			addCriterion("createdon is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedonEqualTo(Date value) {
			addCriterion("createdon =", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonNotEqualTo(Date value) {
			addCriterion("createdon <>", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonGreaterThan(Date value) {
			addCriterion("createdon >", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonGreaterThanOrEqualTo(Date value) {
			addCriterion("createdon >=", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonLessThan(Date value) {
			addCriterion("createdon <", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonLessThanOrEqualTo(Date value) {
			addCriterion("createdon <=", value, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonIn(List<Date> values) {
			addCriterion("createdon in", values, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonNotIn(List<Date> values) {
			addCriterion("createdon not in", values, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonBetween(Date value1, Date value2) {
			addCriterion("createdon between", value1, value2, "createdon");
			return (Criteria) this;
		}

		public Criteria andCreatedonNotBetween(Date value1, Date value2) {
			addCriterion("createdon not between", value1, value2, "createdon");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyIsNull() {
			addCriterion("updatedby is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyIsNotNull() {
			addCriterion("updatedby is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyEqualTo(String value) {
			addCriterion("updatedby =", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotEqualTo(String value) {
			addCriterion("updatedby <>", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyGreaterThan(String value) {
			addCriterion("updatedby >", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("updatedby >=", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyLessThan(String value) {
			addCriterion("updatedby <", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyLessThanOrEqualTo(String value) {
			addCriterion("updatedby <=", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyLike(String value) {
			addCriterion("updatedby like", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotLike(String value) {
			addCriterion("updatedby not like", value, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyIn(List<String> values) {
			addCriterion("updatedby in", values, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotIn(List<String> values) {
			addCriterion("updatedby not in", values, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyBetween(String value1, String value2) {
			addCriterion("updatedby between", value1, value2, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedbyNotBetween(String value1, String value2) {
			addCriterion("updatedby not between", value1, value2, "updatedby");
			return (Criteria) this;
		}

		public Criteria andUpdatedonIsNull() {
			addCriterion("updatedon is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedonIsNotNull() {
			addCriterion("updatedon is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedonEqualTo(Date value) {
			addCriterion("updatedon =", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonNotEqualTo(Date value) {
			addCriterion("updatedon <>", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonGreaterThan(Date value) {
			addCriterion("updatedon >", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonGreaterThanOrEqualTo(Date value) {
			addCriterion("updatedon >=", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonLessThan(Date value) {
			addCriterion("updatedon <", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonLessThanOrEqualTo(Date value) {
			addCriterion("updatedon <=", value, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonIn(List<Date> values) {
			addCriterion("updatedon in", values, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonNotIn(List<Date> values) {
			addCriterion("updatedon not in", values, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonBetween(Date value1, Date value2) {
			addCriterion("updatedon between", value1, value2, "updatedon");
			return (Criteria) this;
		}

		public Criteria andUpdatedonNotBetween(Date value1, Date value2) {
			addCriterion("updatedon not between", value1, value2, "updatedon");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customeraddress
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 16 22:52:26 SGT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}