package com.JJ.model;

import java.math.BigDecimal;

public class Discount {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.discountId
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private Integer discountid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.promoId
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private Integer promoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.discountName
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private String discountname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.discountType
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private String discounttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.discountValue
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private BigDecimal discountvalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.deleteInd
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private String deleteind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column discount.applyType
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	private String applytype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.discountId
	 * @return  the value of discount.discountId
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public Integer getDiscountid() {
		return discountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.discountId
	 * @param discountid  the value for discount.discountId
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setDiscountid(Integer discountid) {
		this.discountid = discountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.promoId
	 * @return  the value of discount.promoId
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public Integer getPromoid() {
		return promoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.promoId
	 * @param promoid  the value for discount.promoId
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setPromoid(Integer promoid) {
		this.promoid = promoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.discountName
	 * @return  the value of discount.discountName
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public String getDiscountname() {
		return discountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.discountName
	 * @param discountname  the value for discount.discountName
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setDiscountname(String discountname) {
		this.discountname = discountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.discountType
	 * @return  the value of discount.discountType
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public String getDiscounttype() {
		return discounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.discountType
	 * @param discounttype  the value for discount.discountType
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setDiscounttype(String discounttype) {
		this.discounttype = discounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.discountValue
	 * @return  the value of discount.discountValue
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public BigDecimal getDiscountvalue() {
		return discountvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.discountValue
	 * @param discountvalue  the value for discount.discountValue
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setDiscountvalue(BigDecimal discountvalue) {
		this.discountvalue = discountvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.deleteInd
	 * @return  the value of discount.deleteInd
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public String getDeleteind() {
		return deleteind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.deleteInd
	 * @param deleteind  the value for discount.deleteInd
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setDeleteind(String deleteind) {
		this.deleteind = deleteind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column discount.applyType
	 * @return  the value of discount.applyType
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public String getApplytype() {
		return applytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column discount.applyType
	 * @param applytype  the value for discount.applyType
	 * @mbggenerated  Mon Nov 07 21:53:22 SGT 2016
	 */
	public void setApplytype(String applytype) {
		this.applytype = applytype;
	}

	@Override
	public String toString() {
		return "Discount [discountid=" + discountid + ", promoid=" + promoid + ", discountname=" + discountname
				+ ", discounttype=" + discounttype + ", discountvalue=" + discountvalue + ", deleteind=" + deleteind
				+ "]";
	}
}