package com.JJ.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ImagestagingExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public ImagestagingExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andImagestagingidIsNull() {
			addCriterion("imagestagingId is null");
			return (Criteria) this;
		}

		public Criteria andImagestagingidIsNotNull() {
			addCriterion("imagestagingId is not null");
			return (Criteria) this;
		}

		public Criteria andImagestagingidEqualTo(Integer value) {
			addCriterion("imagestagingId =", value, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidNotEqualTo(Integer value) {
			addCriterion("imagestagingId <>", value, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidGreaterThan(Integer value) {
			addCriterion("imagestagingId >", value, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidGreaterThanOrEqualTo(Integer value) {
			addCriterion("imagestagingId >=", value, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidLessThan(Integer value) {
			addCriterion("imagestagingId <", value, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidLessThanOrEqualTo(Integer value) {
			addCriterion("imagestagingId <=", value, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidIn(List<Integer> values) {
			addCriterion("imagestagingId in", values, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidNotIn(List<Integer> values) {
			addCriterion("imagestagingId not in", values, "imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidBetween(Integer value1, Integer value2) {
			addCriterion("imagestagingId between", value1, value2,
					"imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagestagingidNotBetween(Integer value1,
				Integer value2) {
			addCriterion("imagestagingId not between", value1, value2,
					"imagestagingid");
			return (Criteria) this;
		}

		public Criteria andImagenameIsNull() {
			addCriterion("imageName is null");
			return (Criteria) this;
		}

		public Criteria andImagenameIsNotNull() {
			addCriterion("imageName is not null");
			return (Criteria) this;
		}

		public Criteria andImagenameEqualTo(String value) {
			addCriterion("imageName =", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameNotEqualTo(String value) {
			addCriterion("imageName <>", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameGreaterThan(String value) {
			addCriterion("imageName >", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameGreaterThanOrEqualTo(String value) {
			addCriterion("imageName >=", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameLessThan(String value) {
			addCriterion("imageName <", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameLessThanOrEqualTo(String value) {
			addCriterion("imageName <=", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameLike(String value) {
			addCriterion("imageName like", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameNotLike(String value) {
			addCriterion("imageName not like", value, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameIn(List<String> values) {
			addCriterion("imageName in", values, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameNotIn(List<String> values) {
			addCriterion("imageName not in", values, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameBetween(String value1, String value2) {
			addCriterion("imageName between", value1, value2, "imagename");
			return (Criteria) this;
		}

		public Criteria andImagenameNotBetween(String value1, String value2) {
			addCriterion("imageName not between", value1, value2, "imagename");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("createdDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("createdDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("createdDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("createdDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("createdDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("createdDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("createdDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("createdDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("createdDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("createdDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("createdDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("createdDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNull() {
			addCriterion("createdBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIsNotNull() {
			addCriterion("createdBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedbyEqualTo(String value) {
			addCriterion("createdBy =", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotEqualTo(String value) {
			addCriterion("createdBy <>", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThan(String value) {
			addCriterion("createdBy >", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
			addCriterion("createdBy >=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThan(String value) {
			addCriterion("createdBy <", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLessThanOrEqualTo(String value) {
			addCriterion("createdBy <=", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyLike(String value) {
			addCriterion("createdBy like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotLike(String value) {
			addCriterion("createdBy not like", value, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyIn(List<String> values) {
			addCriterion("createdBy in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotIn(List<String> values) {
			addCriterion("createdBy not in", values, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyBetween(String value1, String value2) {
			addCriterion("createdBy between", value1, value2, "createdby");
			return (Criteria) this;
		}

		public Criteria andCreatedbyNotBetween(String value1, String value2) {
			addCriterion("createdBy not between", value1, value2, "createdby");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table imagestaging
	 * @mbggenerated  Tue Nov 08 21:27:59 SGT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table imagestaging
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 07 22:32:26 SGT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}