package com.JJ.model;

import java.util.Date;

public class Imagestaging {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column imagestaging.imageStagingId
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	private Integer imagestagingid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column imagestaging.imageName
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	private String imagename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column imagestaging.createdDate
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column imagestaging.createdBy
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	private String createdby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column imagestaging.image
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	private byte[] image;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column imagestaging.imageStagingId
	 * @return  the value of imagestaging.imageStagingId
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public Integer getImagestagingid() {
		return imagestagingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column imagestaging.imageStagingId
	 * @param imagestagingid  the value for imagestaging.imageStagingId
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public void setImagestagingid(Integer imagestagingid) {
		this.imagestagingid = imagestagingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column imagestaging.imageName
	 * @return  the value of imagestaging.imageName
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public String getImagename() {
		return imagename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column imagestaging.imageName
	 * @param imagename  the value for imagestaging.imageName
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column imagestaging.createdDate
	 * @return  the value of imagestaging.createdDate
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column imagestaging.createdDate
	 * @param createddate  the value for imagestaging.createdDate
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column imagestaging.createdBy
	 * @return  the value of imagestaging.createdBy
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public String getCreatedby() {
		return createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column imagestaging.createdBy
	 * @param createdby  the value for imagestaging.createdBy
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column imagestaging.image
	 * @return  the value of imagestaging.image
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public byte[] getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column imagestaging.image
	 * @param image  the value for imagestaging.image
	 * @mbggenerated  Mon Nov 07 22:47:00 SGT 2016
	 */
	public void setImage(byte[] image) {
		this.image = image;
	}
}