package com.JJ.model;

import java.util.List;
import java.util.Date;

public class Productoption extends Base{

	private Integer productoptionid;
	private String name;
	private Boolean displayind;
	private String deleteind;
	private String createdby;
	private Date createdon;
	private String updatedby;
	private Date updatedon;
	private Integer version;

	public Integer getProductoptionid() {
		return productoptionid;
	}

	public void setProductoptionid(Integer productoptionid) {
		this.productoptionid = productoptionid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getDisplayind() {
		return displayind;
	}

	public void setDisplayind(Boolean displayind) {
		this.displayind = displayind;
	}

	public String getDeleteind() {
		return deleteind;
	}

	public void setDeleteind(String deleteind) {
		this.deleteind = deleteind;
	}

	public String getCreatedby() {
		return createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreatedon() {
		return createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	public String getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdatedon() {
		return updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.deleteInd
	 * @return  the value of productoption.deleteInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */

	public List<Productsuboption> getSubOptionsList() {
		return subOptionsList;
	}

	public void setSubOptionsList(List<Productsuboption> subOptionsList) {
		this.subOptionsList = subOptionsList;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Productoption other = (Productoption) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	//non-db variable
	private List<Productsuboption> subOptionsList;
	
}