package com.JJ.model;

import java.math.BigDecimal;

public class Product extends Base {

	@Override
	public String toString() {
		return "Product [productid=" + productid + ", productname=" + productname + ", unitprice=" + unitprice
				+ ", subcategoryid=" + subcategoryid + ", desciption=" + desciption + ", getDeleteind()="
				+ getDeleteind() + ", getCreatedby()=" + getCreatedby() + ", getCreatedon()=" + getCreatedon()
				+ ", getUpdatedby()=" + getUpdatedby() + ", getUpdatedon()=" + getUpdatedon() + ", getVersion()="
				+ getVersion() + "]";
	}

	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productName
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.unitPrice
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	private BigDecimal unitprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.subcategoryId
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	private Integer subcategoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.desciption
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	private String desciption;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productId
	 * @return  the value of product.productId
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productId
	 * @param productid  the value for product.productId
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productName
	 * @return  the value of product.productName
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productName
	 * @param productname  the value for product.productName
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public void setProductname(String productname) {
		this.productname = productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.unitPrice
	 * @return  the value of product.unitPrice
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public BigDecimal getUnitprice() {
		return unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.unitPrice
	 * @param unitprice  the value for product.unitPrice
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.subcategoryId
	 * @return  the value of product.subcategoryId
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public Integer getSubcategoryid() {
		return subcategoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.subcategoryId
	 * @param subcategoryid  the value for product.subcategoryId
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public void setSubcategoryid(Integer subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.desciption
	 * @return  the value of product.desciption
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public String getDesciption() {
		return desciption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.desciption
	 * @param desciption  the value for product.desciption
	 * @mbggenerated  Wed Nov 09 23:36:09 SGT 2016
	 */
	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}
	public Productsubcategory getSubCategory() {
		return subCategory;
	}

	public void setSubCategory(Productsubcategory subCategory) {
		this.subCategory = subCategory;
	}

	//non-db variable
	private Productsubcategory subCategory;
}