package com.JJ.model;

import java.util.List;
import java.util.Date;

public class Productoption{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.productoptionId
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private Integer productoptionid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.name
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.displayInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private Boolean displayind;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.sequence
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private Integer sequence;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.deleteInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private String deleteind;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.createdby
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private String createdby;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.createdon
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private Date createdon;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.updatedby
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private String updatedby;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.updatedon
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private Date updatedon;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productoption.version
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.productoptionId
	 * @return  the value of productoption.productoptionId
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public Integer getProductoptionid() {
		return productoptionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.productoptionId
	 * @param productoptionid  the value for productoption.productoptionId
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setProductoptionid(Integer productoptionid) {
		this.productoptionid = productoptionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.name
	 * @return  the value of productoption.name
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.name
	 * @param name  the value for productoption.name
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.displayInd
	 * @return  the value of productoption.displayInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public Boolean getDisplayind() {
		return displayind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.displayInd
	 * @param displayind  the value for productoption.displayInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setDisplayind(Boolean displayind) {
		this.displayind = displayind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.sequence
	 * @return  the value of productoption.sequence
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public Integer getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.sequence
	 * @param sequence  the value for productoption.sequence
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.deleteInd
	 * @return  the value of productoption.deleteInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public String getDeleteind() {
		return deleteind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.deleteInd
	 * @param deleteind  the value for productoption.deleteInd
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setDeleteind(String deleteind) {
		this.deleteind = deleteind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.createdby
	 * @return  the value of productoption.createdby
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public String getCreatedby() {
		return createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.createdby
	 * @param createdby  the value for productoption.createdby
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.createdon
	 * @return  the value of productoption.createdon
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public Date getCreatedon() {
		return createdon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.createdon
	 * @param createdon  the value for productoption.createdon
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.updatedby
	 * @return  the value of productoption.updatedby
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public String getUpdatedby() {
		return updatedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.updatedby
	 * @param updatedby  the value for productoption.updatedby
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.updatedon
	 * @return  the value of productoption.updatedon
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public Date getUpdatedon() {
		return updatedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.updatedon
	 * @param updatedon  the value for productoption.updatedon
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productoption.version
	 * @return  the value of productoption.version
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productoption.version
	 * @param version  the value for productoption.version
	 * @mbggenerated  Sun Nov 20 16:47:39 SGT 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public String toString() {
		return "Productoption [productoptionid=" + productoptionid + ", name=" + name + ", displayind=" + displayind
				+ ", sequence=" + sequence + ", getDeleteind()=" + getDeleteind() + ", getCreatedby()=" + getCreatedby()
				+ ", getCreatedon()=" + getCreatedon() + ", getUpdatedby()=" + getUpdatedby() + ", getUpdatedon()="
				+ getUpdatedon() + ", getVersion()=" + getVersion() + "]";
	}

	public List<Productsuboption> getSubOptionsList() {
		return subOptionsList;
	}

	public void setSubOptionsList(List<Productsuboption> subOptionsList) {
		this.subOptionsList = subOptionsList;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Productoption other = (Productoption) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	//non-db variable
	private List<Productsuboption> subOptionsList;
	
}