package com.JJ.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product {

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productid == null) ? 0 : productid.hashCode());
		result = prime * result + ((productname == null) ? 0 : productname.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Product other = (Product) obj;
		if (productid == null) {
			if (other.productid != null)
				return false;
		} else if (!productid.equals(other.productid))
			return false;
		if (productname == null) {
			if (other.productname != null)
				return false;
		} else if (!productname.equals(other.productname))
			return false;
		return true;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productId
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productName
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.unitPrice
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private BigDecimal unitprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.weight
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private Integer weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.subcategoryId
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private Integer subcategoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.desciption
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private String desciption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.deleteInd
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private String deleteind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.createdby
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private String createdby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.createdon
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private Date createdon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updatedby
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private String updatedby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updatedon
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private Date updatedon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.version
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	private Integer version;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productId
	 * @return  the value of product.productId
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productId
	 * @param productid  the value for product.productId
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productName
	 * @return  the value of product.productName
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productName
	 * @param productname  the value for product.productName
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setProductname(String productname) {
		this.productname = productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.unitPrice
	 * @return  the value of product.unitPrice
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public BigDecimal getUnitprice() {
		return unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.unitPrice
	 * @param unitprice  the value for product.unitPrice
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.weight
	 * @return  the value of product.weight
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.weight
	 * @param weight  the value for product.weight
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.subcategoryId
	 * @return  the value of product.subcategoryId
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public Integer getSubcategoryid() {
		return subcategoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.subcategoryId
	 * @param subcategoryid  the value for product.subcategoryId
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setSubcategoryid(Integer subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.desciption
	 * @return  the value of product.desciption
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public String getDesciption() {
		return desciption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.desciption
	 * @param desciption  the value for product.desciption
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.deleteInd
	 * @return  the value of product.deleteInd
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public String getDeleteind() {
		return deleteind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.deleteInd
	 * @param deleteind  the value for product.deleteInd
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setDeleteind(String deleteind) {
		this.deleteind = deleteind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.createdby
	 * @return  the value of product.createdby
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public String getCreatedby() {
		return createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.createdby
	 * @param createdby  the value for product.createdby
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.createdon
	 * @return  the value of product.createdon
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public Date getCreatedon() {
		return createdon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.createdon
	 * @param createdon  the value for product.createdon
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updatedby
	 * @return  the value of product.updatedby
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public String getUpdatedby() {
		return updatedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updatedby
	 * @param updatedby  the value for product.updatedby
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updatedon
	 * @return  the value of product.updatedon
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public Date getUpdatedon() {
		return updatedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updatedon
	 * @param updatedon  the value for product.updatedon
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.version
	 * @return  the value of product.version
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.version
	 * @param version  the value for product.version
	 * @mbggenerated  Wed Nov 23 22:05:12 SGT 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public String toString() {
		return "Product [productid=" + productid + ", productname=" + productname + ", unitprice=" + unitprice
				+ ", subcategoryid=" + subcategoryid + ", desciption=" + desciption + ", getDeleteind()="
				+ getDeleteind() + ", getCreatedby()=" + getCreatedby() + ", getCreatedon()=" + getCreatedon()
				+ ", getUpdatedby()=" + getUpdatedby() + ", getUpdatedon()=" + getUpdatedon() + ", getVersion()="
				+ getVersion() + "]";
	}

	public Productsubcategory getSubCategory() {
		return subCategory;
	}

	public void setSubCategory(Productsubcategory subCategory) {
		this.subCategory = subCategory;
	}

	//non-db variable
	private Productsubcategory subCategory;
}