package com.JJ.model;

public class Productimage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productimage.imageId
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	private Integer imageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productimage.productId
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productimage.imageName
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	private String imagename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productimage.sequence
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	private Integer sequence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productimage.displayInd
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	private Boolean displayind;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productimage.imageId
	 * @return  the value of productimage.imageId
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public Integer getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productimage.imageId
	 * @param imageid  the value for productimage.imageId
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public void setImageid(Integer imageid) {
		this.imageid = imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productimage.productId
	 * @return  the value of productimage.productId
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productimage.productId
	 * @param productid  the value for productimage.productId
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productimage.imageName
	 * @return  the value of productimage.imageName
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public String getImagename() {
		return imagename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productimage.imageName
	 * @param imagename  the value for productimage.imageName
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productimage.sequence
	 * @return  the value of productimage.sequence
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public Integer getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productimage.sequence
	 * @param sequence  the value for productimage.sequence
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productimage.displayInd
	 * @return  the value of productimage.displayInd
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public Boolean getDisplayind() {
		return displayind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productimage.displayInd
	 * @param displayind  the value for productimage.displayInd
	 * @mbggenerated  Mon Nov 07 22:13:50 SGT 2016
	 */
	public void setDisplayind(Boolean displayind) {
		this.displayind = displayind;
	}
}