package com.JJ.model;

import java.util.Date;

public class Promotion extends Base{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column promotion.promotionId
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	private Integer promotionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column promotion.promotionName
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	private String promotionname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column promotion.promotionMessage
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	private String promotionmessage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column promotion.promotionStartDate
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	private Date promotionstartdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column promotion.promotionEndDate
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	private Date promotionenddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column promotion.isActive
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	private Boolean isactive;
	
	public Integer getPromotionid() {
		return promotionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column promotion.promotionId
	 * @param promotionid  the value for promotion.promotionId
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public void setPromotionid(Integer promotionid) {
		this.promotionid = promotionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column promotion.promotionName
	 * @return  the value of promotion.promotionName
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public String getPromotionname() {
		return promotionname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column promotion.promotionName
	 * @param promotionname  the value for promotion.promotionName
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public void setPromotionname(String promotionname) {
		this.promotionname = promotionname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column promotion.promotionMessage
	 * @return  the value of promotion.promotionMessage
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public String getPromotionmessage() {
		return promotionmessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column promotion.promotionMessage
	 * @param promotionmessage  the value for promotion.promotionMessage
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public void setPromotionmessage(String promotionmessage) {
		this.promotionmessage = promotionmessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column promotion.promotionStartDate
	 * @return  the value of promotion.promotionStartDate
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public Date getPromotionstartdate() {
		return promotionstartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column promotion.promotionStartDate
	 * @param promotionstartdate  the value for promotion.promotionStartDate
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public void setPromotionstartdate(Date promotionstartdate) {
		this.promotionstartdate = promotionstartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column promotion.promotionEndDate
	 * @return  the value of promotion.promotionEndDate
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public Date getPromotionenddate() {
		return promotionenddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column promotion.promotionEndDate
	 * @param promotionenddate  the value for promotion.promotionEndDate
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public void setPromotionenddate(Date promotionenddate) {
		this.promotionenddate = promotionenddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column promotion.isActive
	 * @return  the value of promotion.isActive
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public Boolean getIsactive() {
		return isactive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column promotion.isActive
	 * @param isactive  the value for promotion.isActive
	 * @mbggenerated  Wed Nov 09 23:39:17 SGT 2016
	 */
	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}


	//non db fields
	private String promotionperiod;
	
	public String getPromotionperiod() {
		return promotionperiod;
	}

	public void setPromotionperiod(String promotionperiod) {
		this.promotionperiod = promotionperiod;
	}
    
}