package com.JJ.model;

public class Role extends Base{
    @Override
	public String toString() {
		return "Role [id=" + id + ", name=" + name + ", getDeleteind()=" + getDeleteind() + ", getCreatedby()="
				+ getCreatedby() + ", getCreatedon()=" + getCreatedon() + ", getUpdatedby()=" + getUpdatedby()
				+ ", getUpdatedon()=" + getUpdatedon() + ", getVersion()=" + getVersion() + "]";
	}


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
	 * @mbggenerated  Wed Nov 09 23:39:27 SGT 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.name
	 * @mbggenerated  Wed Nov 09 23:39:27 SGT 2016
	 */
	private String name;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
	 * @return  the value of role.id
	 * @mbggenerated  Wed Nov 09 23:39:27 SGT 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
	 * @param id  the value for role.id
	 * @mbggenerated  Wed Nov 09 23:39:27 SGT 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.name
	 * @return  the value of role.name
	 * @mbggenerated  Wed Nov 09 23:39:27 SGT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.name
	 * @param name  the value for role.name
	 * @mbggenerated  Wed Nov 09 23:39:27 SGT 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	
}