package com.JJ.model;

public class Submodulepermissiontype extends Base{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public String toString() {
		return "Submodulepermissiontype [id=" + id + ", submoduleid=" + submoduleid + ", permissiontype="
				+ permissiontype + ", seqno=" + seqno + ", url=" + url + ", getDeleteind()=" + getDeleteind()
				+ ", getCreatedby()=" + getCreatedby() + ", getCreatedon()=" + getCreatedon() + ", getUpdatedby()="
				+ getUpdatedby() + ", getUpdatedon()=" + getUpdatedon() + ", getVersion()=" + getVersion() + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column submodulepermissiontype.id
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column submodulepermissiontype.submoduleid
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	private String submoduleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column submodulepermissiontype.permissiontype
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	private String permissiontype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column submodulepermissiontype.seqNo
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	private String seqno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column submodulepermissiontype.url
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column submodulepermissiontype.id
	 * @return  the value of submodulepermissiontype.id
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column submodulepermissiontype.id
	 * @param id  the value for submodulepermissiontype.id
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column submodulepermissiontype.submoduleid
	 * @return  the value of submodulepermissiontype.submoduleid
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public String getSubmoduleid() {
		return submoduleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column submodulepermissiontype.submoduleid
	 * @param submoduleid  the value for submodulepermissiontype.submoduleid
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public void setSubmoduleid(String submoduleid) {
		this.submoduleid = submoduleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column submodulepermissiontype.permissiontype
	 * @return  the value of submodulepermissiontype.permissiontype
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public String getPermissiontype() {
		return permissiontype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column submodulepermissiontype.permissiontype
	 * @param permissiontype  the value for submodulepermissiontype.permissiontype
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public void setPermissiontype(String permissiontype) {
		this.permissiontype = permissiontype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column submodulepermissiontype.seqNo
	 * @return  the value of submodulepermissiontype.seqNo
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public String getSeqno() {
		return seqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column submodulepermissiontype.seqNo
	 * @param seqno  the value for submodulepermissiontype.seqNo
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public void setSeqno(String seqno) {
		this.seqno = seqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column submodulepermissiontype.url
	 * @return  the value of submodulepermissiontype.url
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column submodulepermissiontype.url
	 * @param url  the value for submodulepermissiontype.url
	 * @mbggenerated  Wed Nov 09 23:39:51 SGT 2016
	 */
	public void setUrl(String url) {
		this.url = url;
	}

}