package com.JJ.model;

public class Submodulepermission extends SubmodulepermissionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submodulepermission.permission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submodulepermission.permission
     *
     * @return the value of submodulepermission.permission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submodulepermission.permission
     *
     * @param permission the value for submodulepermission.permission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }
}