package com.JJ.model;

public class UserRole extends Base{

	@Override
	public String toString() {
		return "UserRole [userid=" + userid + ", roleid=" + roleid + ", getDeleteind()=" + getDeleteind()
				+ ", getCreatedby()=" + getCreatedby() + ", getCreatedon()=" + getCreatedon() + ", getUpdatedby()="
				+ getUpdatedby() + ", getUpdatedon()=" + getUpdatedon() + ", getVersion()=" + getVersion() + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.userid
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.roleid
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.userid
	 * @return  the value of user_role.userid
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.userid
	 * @param userid  the value for user_role.userid
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.roleid
	 * @return  the value of user_role.roleid
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.roleid
	 * @param roleid  the value for user_role.roleid
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
}