package com.JJ.model;

import java.util.Date;

public class UserRole extends UserRoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.createdby
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.createdon
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    private Date createdon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.updatedby
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    private String updatedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.updatedon
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    private Date updatedon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.version
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    private Byte version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.createdby
     *
     * @return the value of user_role.createdby
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.createdby
     *
     * @param createdby the value for user_role.createdby
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.createdon
     *
     * @return the value of user_role.createdon
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.createdon
     *
     * @param createdon the value for user_role.createdon
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.updatedby
     *
     * @return the value of user_role.updatedby
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public String getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.updatedby
     *
     * @param updatedby the value for user_role.updatedby
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.updatedon
     *
     * @return the value of user_role.updatedon
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public Date getUpdatedon() {
        return updatedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.updatedon
     *
     * @param updatedon the value for user_role.updatedon
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.version
     *
     * @return the value of user_role.version
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.version
     *
     * @param version the value for user_role.version
     *
     * @mbggenerated Wed Oct 12 22:49:47 SGT 2016
     */
    public void setVersion(Byte version) {
        this.version = version;
    }
}