package com.JJ.dao;

import com.JJ.model.Adminmodule;
import com.JJ.model.AdminmoduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminmoduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int countByExample(AdminmoduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int deleteByExample(AdminmoduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int insert(Adminmodule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int insertSelective(Adminmodule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	List<Adminmodule> selectByExample(AdminmoduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	Adminmodule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int updateByExampleSelective(@Param("record") Adminmodule record,
			@Param("example") AdminmoduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int updateByExample(@Param("record") Adminmodule record,
			@Param("example") AdminmoduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int updateByPrimaryKeySelective(Adminmodule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adminmodule
	 * @mbggenerated  Sat Oct 08 13:21:30 SGT 2016
	 */
	int updateByPrimaryKey(Adminmodule record);
}