package com.JJ.dao;

import com.JJ.model.BatchproductRs;
import com.JJ.model.BatchproductRsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchproductRsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int countByExample(BatchproductRsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int deleteByExample(BatchproductRsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int deleteByPrimaryKey(Integer batchproductid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int insert(BatchproductRs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int insertSelective(BatchproductRs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	List<BatchproductRs> selectByExample(BatchproductRsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	BatchproductRs selectByPrimaryKey(Integer batchproductid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int updateByExampleSelective(@Param("record") BatchproductRs record,
			@Param("example") BatchproductRsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int updateByExample(@Param("record") BatchproductRs record, @Param("example") BatchproductRsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int updateByPrimaryKeySelective(BatchproductRs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchproduct_rs
	 * @mbggenerated  Tue Nov 29 20:56:01 SGT 2016
	 */
	int updateByPrimaryKey(BatchproductRs record);
}