package com.JJ.dao;

import com.JJ.model.Batchstockintake;
import com.JJ.model.BatchstockintakeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchstockintakeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int countByExample(BatchstockintakeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int deleteByExample(BatchstockintakeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int deleteByPrimaryKey(Integer batchid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int insert(Batchstockintake record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int insertSelective(Batchstockintake record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	List<Batchstockintake> selectByExample(BatchstockintakeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	Batchstockintake selectByPrimaryKey(Integer batchid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int updateByExampleSelective(@Param("record") Batchstockintake record,
			@Param("example") BatchstockintakeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int updateByExample(@Param("record") Batchstockintake record, @Param("example") BatchstockintakeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int updateByPrimaryKeySelective(Batchstockintake record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table batchstockintake
	 * @mbggenerated  Sun Nov 20 22:23:18 SGT 2016
	 */
	int updateByPrimaryKey(Batchstockintake record);
}