package com.JJ.dao;

import com.JJ.model.Customeraddress;
import com.JJ.model.CustomeraddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomeraddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int countByExample(CustomeraddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int deleteByExample(CustomeraddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int deleteByPrimaryKey(Integer addressid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int insert(Customeraddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int insertSelective(Customeraddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	List<Customeraddress> selectByExample(CustomeraddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	Customeraddress selectByPrimaryKey(Integer addressid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int updateByExampleSelective(@Param("record") Customeraddress record,
			@Param("example") CustomeraddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int updateByExample(@Param("record") Customeraddress record, @Param("example") CustomeraddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int updateByPrimaryKeySelective(Customeraddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customeraddress
	 * @mbggenerated  Wed Nov 16 23:04:04 SGT 2016
	 */
	int updateByPrimaryKey(Customeraddress record);
}