package com.JJ.dao;

import com.JJ.model.Productsubcategory;
import com.JJ.model.ProductsubcategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductsubcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int countByExample(ProductsubcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int deleteByExample(ProductsubcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int insert(Productsubcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int insertSelective(Productsubcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    List<Productsubcategory> selectByExample(ProductsubcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    Productsubcategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int updateByExampleSelective(@Param("record") Productsubcategory record, @Param("example") ProductsubcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int updateByExample(@Param("record") Productsubcategory record, @Param("example") ProductsubcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int updateByPrimaryKeySelective(Productsubcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productsubcategory
     *
     * @mbggenerated Sat Oct 29 23:10:05 SGT 2016
     */
    int updateByPrimaryKey(Productsubcategory record);
}