package com.JJ.dao;

import com.JJ.model.Productinventory;
import com.JJ.model.ProductinventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductinventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int countByExample(ProductinventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int deleteByExample(ProductinventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int deleteByPrimaryKey(Integer productinventoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int insert(Productinventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int insertSelective(Productinventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    List<Productinventory> selectByExample(ProductinventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    Productinventory selectByPrimaryKey(Integer productinventoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int updateByExampleSelective(@Param("record") Productinventory record, @Param("example") ProductinventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int updateByExample(@Param("record") Productinventory record, @Param("example") ProductinventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int updateByPrimaryKeySelective(Productinventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinventory
     *
     * @mbggenerated Sun Mar 05 14:57:59 SGT 2017
     */
    int updateByPrimaryKey(Productinventory record);
}