package com.JJ.dao;

import com.JJ.model.RolesToPermission;
import com.JJ.model.Submodulepermission;
import com.JJ.model.SubmodulepermissionExample;
import com.JJ.model.SubmodulepermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubmodulepermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int countByExample(SubmodulepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int deleteByExample(SubmodulepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int deleteByPrimaryKey(SubmodulepermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int insert(Submodulepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int insertSelective(Submodulepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    List<Submodulepermission> selectByExample(SubmodulepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    Submodulepermission selectByPrimaryKey(SubmodulepermissionKey key);
    
    List<RolesToPermission> getRolesToPermission (String submoduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int updateByExampleSelective(@Param("record") Submodulepermission record, @Param("example") SubmodulepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int updateByExample(@Param("record") Submodulepermission record, @Param("example") SubmodulepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int updateByPrimaryKeySelective(Submodulepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submodulepermission
     *
     * @mbggenerated Sun Oct 16 19:33:59 SGT 2016
     */
    int updateByPrimaryKey(Submodulepermission record);
}