package com.JJ.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.JJ.model.RolesToPermission;
import com.JJ.model.SubmodulepermissionExample;
import com.JJ.model.Submodulepermission;

public interface SubmodulepermissionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int countByExample(SubmodulepermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int deleteByExample(SubmodulepermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int deleteByPrimaryKey(Submodulepermission key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int insert(Submodulepermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int insertSelective(Submodulepermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	List<Submodulepermission> selectByExample(SubmodulepermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	Submodulepermission selectByPrimaryKey(Submodulepermission key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int updateByExampleSelective(@Param("record") Submodulepermission record,
			@Param("example") SubmodulepermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int updateByExample(@Param("record") Submodulepermission record,
			@Param("example") SubmodulepermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int updateByPrimaryKeySelective(Submodulepermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table submodulepermission
	 * @mbggenerated  Wed Nov 09 23:39:44 SGT 2016
	 */
	int updateByPrimaryKey(Submodulepermission record);

	List<RolesToPermission> getRolesToPermission (String submoduleid);
	
	List<Submodulepermission> getSubmodulePermissionByRoleIdList (Map roleList);
	
}