package com.JJ.dao;

import com.JJ.model.RolesToAssign;
import com.JJ.model.UserRole;
import com.JJ.model.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int countByExample(UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int deleteByExample(UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int deleteByPrimaryKey(UserRole key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int insert(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int insertSelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	List<UserRole> selectByExample(UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	UserRole selectByPrimaryKey(UserRole key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int updateByPrimaryKeySelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
	 * @mbggenerated  Wed Nov 09 23:40:12 SGT 2016
	 */
	int updateByPrimaryKey(UserRole record);

	List<RolesToAssign> getRolesToAssign (String userid);
}